version: '3'

services:
  internet-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internet-monitor
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TARGET=8.8.8.8
      - INTERVAL=5
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: ["-port", "8080", "-target", "8.8.8.8", "-interval", "5", "-data-dir", "/app/data", "-static-dir", "/app/web/static", "-templates-dir", "/app/web/templates"] 